version: '3.9'
services:
  mariadb_10_6:
    image: mariadb_10_6             # beri nama image hasil build
    build: mariadb_10_6                  # direktori Dockerfile
    container_name: 3306_mariadb      # beri nama container
    hostname: 3306_mariadb            # beri nama hostname
    ports:
      - 3306:3306
    networks:
      - devnetwork
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=

networks:
  devnetwork:
    name: devnetwork
    external: true

