version: '3.9'
services:
  postgres_16_3:
    image: postgres_16_3             # beri nama image hasil build
    build: postgres_16_3                  # direktori Dockerfile
    container_name: postgres_16_3      # beri nama container
    hostname: postgres_16_3            # beri nama hostname
    ports:
      - 5432:5432
    restart: always  
    networks:
      - devnetwork
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  devnetwork:
    name: devnetwork
    external: true

