version: '3.9'

services:
  webserver_8_1:
    image: webserver_8_1 
    build: webserver_8_1
    container_name: webserver_8_1
    hostname: webserver_8_1
    ports:
    - 8000:80
    networks:
      - devnetwork 
    working_dir: /var/www/html

networks:
  devnetwork:
    name: devnetwork
    external: true

